### ISSUE TITLE
MISP.py not pulling information from STIX package title or description

### ISSUE THREAD

**Issue by robertnixon2003** [certau/cti-toolkit#20]
misp.py is not pulling the information for the MISP event from the package by default

INFO:root:Publishing results to MISP
Traceback (most recent call last):
  File "/usr/local/bin/stixtransclient.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/certau/scripts/stixtransclient.py", line 547, in main
    _process_package(package, transform_class, transform_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/certau/scripts/stixtransclient.py", line 370, in _process_package
    transform.publish()
  File "/usr/local/lib/python2.7/dist-packages/certau/transform/misp.py", line 257, in publish
    self.init_misp_event()
  File "/usr/local/lib/python2.7/dist-packages/certau/transform/misp.py", line 194, in init_misp_event
    date=timestamp.strftime('%Y-%m-%d'),
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 430, in new_event
    misp_event = self._prepare_full_event(distribution, threat_level_id, analysis, info, date, published, orgc_id, org_id, sharing_group_id)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 264, in _prepare_full_event
    analysis=analysis, date=date, orgc_id=orgc_id, org_id=org_id, sharing_group_id=sharing_group_id)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py", line 456, in from_dict
    raise NewAttributeError('The info field of the new event is required.')

**Comment by certau-user** [comment]
Hi @robertnixon2003, it's a little hard to say exactly what the cause of this issue is without a little more context. One possibility is that the STIX package has no title or description, leaving nothing to put in MISP's information field. To get around this you can try specifying a value for this field manually using the `--misp-info` configuration option.
