### ISSUE TITLE
Installation fails installing from pip RHEL 7

### ISSUE THREAD

**Issue by jezkerwin** [certau/cti-toolkit#21]
When installing on RHEL 7 MISP instance the following error is returning when executing 
>pip install cti-toolkit

*OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/stix-1.1.1.4-py2.7.egg'*

--[ Full install trace ]--

 pip install cti-toolkit
Collecting cti-toolkit
  Downloading cti_toolkit-1.1.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib64/python2.7/site-packages (from cti-toolkit)
Collecting libtaxii (from cti-toolkit)
  Downloading libtaxii-1.1.111-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 1.3MB/s
Requirement already satisfied (use --upgrade to upgrade): mixbox in /usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg (from cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): pymisp>=2.4.71 in /usr/lib/python2.7/site-packages (from cti-toolkit)
Collecting configargparse (from cti-toolkit)
  Downloading ConfigArgParse-0.13.0.tar.gz
Collecting stix-ramrod (from cti-toolkit)
  Downloading stix-ramrod-1.2.0.zip (76kB)
    100% |████████████████████████████████| 81kB 1.6MB/s
Collecting cybox==2.1.0.13 (from cti-toolkit)
  Downloading cybox-2.1.0.13.tar.gz (478kB)
    100% |████████████████████████████████| 481kB 997kB/s
Collecting stix==1.1.1.8 (from cti-toolkit)
  Downloading stix-1.1.1.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 973kB/s
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.7/site-packages (from libtaxii->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=1.4.1 in /usr/lib/python2.7/site-packages (from libtaxii->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): ordered-set in /usr/lib/python2.7/site-packages/ordered_set-2.0.2-py2.7.egg (from mixbox->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): weakrefmethod>=1.0.3 in /usr/lib/python2.7/site-packages/weakrefmethod-1.0.3-py2.7.egg (from mixbox->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /usr/lib/python2.7/site-packages (from pymisp>=2.4.71->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=36.4 in /usr/lib/python2.7/site-packages (from pymisp>=2.4.71->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->cti-toolkit)
Requirement already satisfied (use --upgrade to upgrade): functools32; python_version == "2.7" in /usr/lib/python2.7/site-packages (from jsonschema->pymisp>=2.4.71->cti-toolkit)
Installing collected packages: libtaxii, configargparse, stix-ramrod, cybox, stix, cti-toolkit
  Running setup.py install for configargparse ... done
  Running setup.py install for stix-ramrod ... done
  Found existing installation: cybox 2.1.0.12
    Uninstalling cybox-2.1.0.12:
      Successfully uninstalled cybox-2.1.0.12
  Running setup.py install for cybox ... done
  Found existing installation: stix 1.1.1.4
    Uninstalling stix-1.1.1.4:
      Successfully uninstalled stix-1.1.1.4
Successfully installed configargparse cti-toolkit cybox libtaxii stix stix-ramrod
Traceback (most recent call last):
  File "/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 220, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1942, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/stix-1.1.1.4-py2.7.egg'

**Comment by certau-user** [comment]
Hey @jezkerwin can you please try installing stix separately, i.e.

`pip install stix==1.1.1.8`

and let me know if that helps?

**Comment by jezkerwin** [comment]
I created a brand new virtualenv to contain the cti-toolkit.
While installing, I'm now getting the following error.

pip install stix==1.1.1.8
Downloading/unpacking stix==1.1.1.8
  Could not find a version that satisfies the requirement stix==1.1.1.8 (from versions: 1.0.1.0, 1.0.1.0, 1.0.1.1, 1.0.1.1, 1.1.0.0, 1.1.0.0, 1.1.0.1, 1.1.0.1, 1.1.0.2, 1.1.0.2, 1.1.0.3, 1.1.0.3, 1.1.0.4, 1.1.0.4, 1.1.0.5, 1.1.0.5, 1.1.0.6, 1.1.0.6, 1.1.1.0, 1.1.1.0, 1.1.1.1, 1.1.1.1, 1.1.1.2, 1.1.1.2, 1.1.1.3, 1.1.1.3, 1.1.1.4, 1.1.1.4, 1.1.1.5, 1.1.1.5, 1.1.1.6, 1.1.1.6, 1.1.1.6.dev0, 1.1.1.6.dev0, 1.1.1.6.dev1, 1.1.1.6.dev1, 1.1.1.6.dev2, 1.1.1.6.dev2, 1.1.1.7, 1.1.1.7, 1.2.0.0, 1.2.0.0, 1.2.0.1, 1.2.0.1, 1.2.0.1.dev0, 1.2.0.1.dev0, 1.2.0.1.dev1, 1.2.0.1.dev1, 1.2.0.2, 1.2.0.2, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0a6, 1.0.0a6, 1.0.0a7, 1.0.0a7)
Cleaning up...
No distributions matching the version for stix==1.1.1.8
Storing complete log in /root/.pip/pip.log
